name: Deploy

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      -
        name: Build
        run: |
          npm install
          npm run build:gh-pages
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}

